Chapter 3
NozomiSugiyama/study-golang pull request #3
Opened 2019-05-16 07:27 UTC by NozomiSugiyama

# フォームを作ろう
## DBへの保存
ローカルのDBサーバーで研修用のdatabaseを追加
```
create database study_golang
```

**※DBアクセスのテンプレートを渡すのでここまで来たら連絡ください**

DBへの保存はGORMの使い方を参考にしてください
http://gorm.io/docs/index.html

## 演習課題
簡単な会員登録フォームを作成しよう。
登録内容: 氏名、生年月日、メールアドレス、電話番号
asset配下にフォームを用意してapiで保存する

## 学習内容
- Go言語に置ける Array Sliceの仕組み
- gormの利用方法

2019-05-16 07:35 UTC, NozomiSugiyama commented on chap3/model/index.go
> +type Session = gorm.DB
リファクタリングを楽にするためにtype aliasを行う

2019-05-16 07:45 UTC, NozomiSugiyama commented on chap3/controller/user.go
> +	resultUsers := make([]User, 0, len(users))
Modelの依存をさせないために、構造体の変更を行う。
アロケートの回数を少しでも減らすためにcapacityを最初に指定したUserのスライスを作成

2019-05-16 07:49 UTC, NozomiSugiyama commented
Chapter-4では、APIはJSONのみ対応へと修正する予定です。

2019-05-16 08:38 UTC, yamakii reviewed
レビューのコメントです

2019-05-16 08:38 UTC, yamakii commented on chap3/model/user.go
> +
```
type UserRepository struct {
 Session gorm.DB
}
```

2019-05-16 08:38 UTC, yamakii commented on chap3/model/user.go
> +func CreateUser(session *Session, user *User) error {
UserRepositoryのメソッドに変更

2019-05-16 08:38 UTC, yamakii commented on chap3/main.go
> +
type Handler struct {
  Controller *controller.Controller
}

func (h * Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {

2019-05-16 08:38 UTC, yamakii commented on chap3/controller/user.go
> +
type Controller struct {
    UserRepository *model.UserRepository
}

2019-05-16 08:38 UTC, yamakii commented on chap3/controller/user.go
> +func ListUsers(session *model.Session) ([]User, error) {
Controllerのメソッドにします

2019-05-16 08:38 UTC, yamakii commented on chap3/main.go
> +	}
repo := &model.UserRepository{db: session}
Ctl := controller.Controller{ UserRepository: repo}
handler := Handler{ Controller: ctl}

2019-05-16 08:38 UTC, yamakii commented on chap3/main.go
> +	http.HandleFunc("/wep/users", usersHandler)
```suggestion
	http.HandleFunc("/wep/users", handler)
```

2019-05-17 01:49 UTC, NozomiSugiyama commented
昨日教えていただいた内容を元に、修正を行いました。

2019-05-17 02:08 UTC, yamakii requested changes

2019-05-17 02:08 UTC, yamakii commented on chap3/main.go
> +	http.HandleFunc("/wep/users", handler.UsersHandler)
http.Handleで実装するようにしてみてください！

2019-05-17 02:20 UTC, yamakii approved these changes

2019-05-17 02:21 UTC, merged